---
title: "ADRN Severity EOS PRS"
author: "Corey Cox"
date: "4/19/2021"
output: 
  html_document:
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(scales) # masks purrr::discard, readr::col_factor
library(ggsignif)
library(fmsb)
library(pROC)# masks fmsb::roc, stats::(cov, smooth, var)
library(table1, include.only = "table1") # htmltools overrides rstudio::(print.html, print.shiny.tag, print.shiny.tag.list)

formatCaption <- function(txt) { str_c('<p style="font-weight:bold;font-size:1.5em;">', txt, '<p>') }
source("PRS_violin_plot_cleaned_cc.R")
```

### MEGA EA PRS AD Violin Plot
Create data files for violin plots

```{r EA_MEGA_AD}
# EA Phenotype adjusted by age/sex and batch
EA_phenos <- pheno <- "ADRN_MEGA_EA_1626_adjusted_severity_phenotypes.txt" %>%
  read_tsv(col_types = "dcdcddcdddddd")

prs_mega <- "beta_score_eos_prs_EA_MEGA.profile" %>%
  read_table(col_types = "ccdddd")

prs_EA_MEGA_phenos <- prs_mega %>%
  mutate(SampleID = str_extract(IID, "\\d{10}") %>% as.double) %>%
  left_join(pheno, by = "SampleID") %>%
  filter(! is.na(Pheno_ADNA)) %>%
  mutate(IID = SampleID, Age = AGE, Sex = GENDER, ancestry = "European") %>%
  select(IID, SCORE, Pheno_ADNA, Age, Sex, BATCH, DIAGROUP, EOS, RL, EASI, tIgE, ancestry)

# Rerun clinical characteristics with EA only pulling out ADEH+, ADEH-, and Non-Atopic
prs_EA_MEGA_phenos %>%
  table1(data = ., ~ Sex + Age + BATCH + EOS + tIgE + EASI + EOS + RL | DIAGROUP,
         caption = formatCaption("MEGA European Ancestry Phenotypes and Demographics"))

EA_MEGA_plot_data <- gg_prs_prep_data(prs_EA_MEGA_phenos, SCORE, Pheno_ADNA, Age, Sex, BATCH, DIAGROUP, EOS, RL, EASI, tIgE, ancestry)
gg_prs_auc(EA_MEGA_plot_data)

tmp_plot <- gg_prs_violin(EA_MEGA_plot_data, sev = "EOS", "MEGA EA EOS PRS vs AD Case/Control")
tmp_plot
# gg_prs_violin_labels(tmp_plot, EA_MEGA_plot_data, sev = "EOS", plot_dist_y = 0.13)
```
### MEGA EA EASI, EOS, RL, and tIgE Scatter Plot with Linear Fit

```{r EA_MEGA_scatter}
ggplot(eos_phenos, aes(x=EOS, y=SCORE, color = DIAGROUP)) +
  geom_point() + geom_smooth(method=lm, se=FALSE) +
  ggtitle("MEGA EA EOS PRS SCORE vs ADRN EOS -- Cases & Controls")

gg_r_scatter <- function(.data, score, pheno, color, title_prefix) {
  m <- lm( as.formula(str_c(pheno, " ~ ", score)), .data)
  r2 <- str_c("r2 = ", format(summary(m)$r.squared, digits = 3))

  ggplot(.data, aes_string(x = score, y = pheno, color = color)) +
  geom_point() + geom_smooth(method=lm, se=FALSE) +
    geom_text(label = r2, x = -Inf, y = Inf, hjust = -0.5, vjust = 3) +
  ggtitle(str_c(title_prefix, " -- ", score, " vs ", pheno))
}

eos_phenos_cases <- eos_phenos %>% filter(DIAGROUP != "Non-Atopic")
eos_phenos_cases %>% gg_r_scatter("SCORE", "EOS", "EOS", "MEGA EA Cases EH(+) & EH(-)")
eos_phenos_cases %>% gg_r_scatter("SCORE", "tIgE", "EOS", "MEGA EA Cases EH(+) & EH(-)")
eos_phenos_cases %>% gg_r_scatter("SCORE", "EASI", "EOS", "MEGA EA Cases EH(+) & EH(-)")
eos_phenos_cases %>% gg_r_scatter("SCORE", "RL", "EOS", "MEGA EA Cases EH(+) & EH(-)")

eos_phenos_controls <- eos_phenos %>% filter(DIAGROUP == "Non-Atopic")
eos_phenos_controls %>% gg_r_scatter("SCORE", "EOS", "tIgE", "MEGA EA Controls")

eos_phenos_controls %>% gg_r_scatter("tIgE", "EOS", "SCORE", "MEGA EA Controls")
# Run EOS vs tIgE scatter
```




### MEGA EA EASI, EOS, RL, and tIgE Grouped Violin Plots

```{r EA_MEGA_grouped, eval = F}
eos_grouped_phenos <- eos_phenos %>%
  mutate(RL_group = ifelse(RL < 14.526365, 1, 2),
         # EASI_group = ifelse(EASI < 0.6993143, 1, 2)) %>%
         # EASI_group = ifelse(EASI < 1.017539, 1, 2)) %>%
         EASI_group = ifelse(EASI < 1.3142468, 1, 2),
  
         # tIgE_group = ifelse(tIgE < 1.5085789, 1, 2)) %>%
         # tIgE_group = ifelse(tIgE < 2.1804033, 1, 2)) %>%
         tIgE_group = ifelse(tIgE < 2.9507443, 1, 2),
  
         EOS_group = ifelse(tIgE < 1.98294575, 1, 2)) %>%
         # EOS_group = ifelse(tIgE < 2.29346412, 1, 2)) %>%
         # EOS_group = ifelse(tIgE < 2.59029654, 1, 2)) %>%
  filter(! is.na(tIgE_group))

eos_grouped_phenos %>%
  # mutate(IID = SampleID, true_phens = Pheno_ADNA, PRS = SCORE) %>%
  # mutate(IID = SampleID, true_phens = RL_group, PRS = SCORE) %>%
  mutate(IID = SampleID, true_phens = EOS_group, PRS = SCORE) %>%
  select(IID, true_phens, PRS) %>%
  write_csv("prs_file.txt")

eos_grouped_phenos %>%
  mutate(IID = SampleID, Age = AGE, Sex = GENDER, ancestry = "European") %>%
  select(IID, Age, Sex, RL, EASI, tIgE, ancestry) %>%
  write_csv("severity_file.txt")
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


```{r EA_OMNI_AD}
eos_prs <- read_table("beta_score_eos_prs_EA_OMNI.profile", col_types = "ccdddd")
pheno <- read_tsv("ADRN_MEGA_EA_1626_adjusted_severity_phenotypes.txt", col_types = "dcdcddcdddddd")

eos_phenos <- eos_prs %>%
  mutate(MEGA_ID = str_extract(IID, "LP\\d{7}-DNA_.\\d{2}")) %>%
  left_join(pheno, by = "MEGA_ID") %>%
  filter(! is.na(Pheno_ADNA))

eos_phenos %>%
  mutate(IID = SampleID, true_phens = Pheno_ADNA, PRS = SCORE) %>%
  # mutate(IID = SampleID, true_phens = RL_group, PRS = SCORE) %>%
  select(IID, true_phens, PRS) %>%
  write_csv("prs_file.txt")

eos_phenos %>%
  mutate(IID = SampleID, Age = AGE, Sex = GENDER, ancestry = "European") %>%
  select(IID, Age, Sex, RL, EASI, tIgE, ancestry) %>%
  write_csv("severity_file.txt")

gg_prs_violin_ca("OMNI EA EOS PRS vs AD Case/Control")
```

```{r EA_OMNI_scatter}
ggplot(eos_phenos, aes(x=EOS, y=SCORE, color = DIAGROUP)) +
  geom_point() + geom_smooth(method=lm, se=FALSE) +
  ggtitle("OMNI EA Cases & Controls -- SCORE vs AD")

gg_r_scatter <- function(.data, score, pheno, color, title_prefix) {
  m <- lm( as.formula(str_c(score, " ~ ", pheno)), .data)
  r2 <- str_c("r2 = ", format(summary(m)$r.squared, digits = 3))

  ggplot(.data, aes_string(x = pheno, y = score, color = color)) +
  geom_point() + geom_smooth(method=lm, se=FALSE) +
    geom_text(label = r2, x = -Inf, y = Inf, hjust = -0.5, vjust = 3) +
  ggtitle(str_c(title_prefix, " -- ", score, " vs ", pheno))
}

eos_phenos_cases <- eos_phenos %>% filter(DIAGROUP != "Non-Atopic")
eos_phenos_cases %>% gg_r_scatter("SCORE", "EOS", "tIgE", "OMNI EA Cases EH(+) & EH(-)")
eos_phenos_cases %>% gg_r_scatter("SCORE", "tIgE", "EOS", "OMNI EA Cases EH(+) & EH(-)")
eos_phenos_cases %>% gg_r_scatter("SCORE", "EASI", "EOS", "OMNI EA Cases EH(+) & EH(-)")
eos_phenos_cases %>% gg_r_scatter("SCORE", "RL", "EOS", "OMNI EA Cases EH(+) & EH(-)")

eos_phenos_controls <- eos_phenos %>% filter(DIAGROUP == "Non-Atopic")
eos_phenos_controls %>% gg_r_scatter("SCORE", "EOS", "tIgE", "OMNI EA Controls")
```

```{r EA_OMNI_grouped, eval = FALSE}
eos_grouped_phenos <- eos_phenos %>%
  mutate(RL_group = ifelse(RL < 14.526365, 1, 2),
         # EASI_group = ifelse(EASI < 0.6993143, 1, 2)) %>%
         # EASI_group = ifelse(EASI < 1.017539, 1, 2)) %>%
         EASI_group = ifelse(EASI < 1.3142468, 1, 2),
  
         # tIgE_group = ifelse(tIgE < 1.3377471, 1, 2)) %>%
         # tIgE_group = ifelse(tIgE < 1.9118220, 1, 2)) %>%
         tIgE_group = ifelse(tIgE < 2.8043853, 1, 2)) %>%
  filter(! is.na(tIgE_group))

eos_grouped_phenos %>%
  # mutate(IID = SampleID, true_phens = Pheno_ADNA, PRS = SCORE) %>%
  # mutate(IID = SampleID, true_phens = RL_group, PRS = SCORE) %>%
  mutate(IID = SampleID, true_phens = tIgE_group, PRS = SCORE) %>%
  select(IID, true_phens, PRS) %>%
  write_csv("prs_file.txt")

eos_grouped_phenos %>%
  mutate(IID = SampleID, Age = AGE, Sex = GENDER, ancestry = "European") %>%
  select(IID, Age, Sex, RL, EASI, tIgE, ancestry) %>%
  write_csv("severity_file.txt")
```

# EA MEGA and OMNI 


```{r EA_ALL_AD}
eos_prs_mega <- read_table("beta_score_eos_prs_EA_MEGA.profile", col_types = "ccdddd")
eos_prs_omni <- read_table("beta_score_eos_prs_EA_OMNI.profile", col_types = "ccdddd")
pheno <- read_tsv("ADRN_MEGA_EA_1626_adjusted_severity_phenotypes.txt", col_types = "dcdcddcdddddd")

eos_prs <- bind_rows(eos_prs_mega, eos_prs_omni)

MEGA_ID_regex <- c(
  "WG[:digit:]-DNA_.[:digit:]{2}_[:digit:]{9}[:digit:]?",
  "WG[:digit:]{7}-DNA_.[:digit:]{2}_[:digit:]{10}",
  "LP[:digit:]{7}-DNA_.[:digit:]{2}"
) %>% str_c(collapse = "|")

eos_phenos <- eos_prs %>%
  mutate(MEGA_ID = str_extract(IID, MEGA_ID_regex)) %>%
  left_join(pheno, by = "MEGA_ID") %>%
  filter(! is.na(Pheno_ADNA))

# eos_phenos <- eos_prs %>%
#   mutate(MEGA_ID = str_extract(IID, "LP\\d{7}-DNA_.\\d{2}")) %>%
#   left_join(pheno, by = "MEGA_ID") %>%
#   filter(! is.na(Pheno_ADNA))

eos_phenos %>%
  mutate(IID = MEGA_ID, true_phens = Pheno_ADNA, PRS = SCORE) %>%
  # mutate(IID = SampleID, true_phens = RL_group, PRS = SCORE) %>%
  select(IID, true_phens, PRS) %>%
  write_csv("prs_file.txt")

eos_phenos %>%
  mutate(IID = SampleID, Age = AGE, Sex = GENDER, ancestry = "European") %>%
  select(IID, Age, Sex, RL, EASI, tIgE, ancestry) %>%
  write_csv("severity_file.txt")

gg_prs_violin_ca("OMNI EA EOS PRS vs AD Case/Control")
```

```{r EA_ALL_scatter}
ggplot(eos_phenos, aes(x=EOS, y=SCORE, color = DIAGROUP)) +
  geom_point() + geom_smooth(method=lm, se=FALSE) +
  ggtitle("OMNI EA Cases & Controls -- SCORE vs AD")

gg_r_scatter <- function(.data, score, pheno, color, title_prefix) {
  m <- lm( as.formula(str_c(score, " ~ ", pheno)), .data)
  r2 <- str_c("r2 = ", format(summary(m)$r.squared, digits = 3))

  ggplot(.data, aes_string(x = pheno, y = score, color = color)) +
    geom_point() + geom_smooth(method=lm, se=FALSE) +
    geom_text(label = r2, x = -Inf, y = Inf, hjust = -0.5, vjust = 3) +
    ggtitle(str_c(title_prefix, " -- ", score, " vs ", pheno))
}

eos_phenos_cases <- eos_phenos %>% filter(DIAGROUP != "Non-Atopic")
eos_phenos_cases %>% gg_r_scatter("SCORE", "EOS", "tIgE", "OMNI EA Cases EH(+) & EH(-)")
eos_phenos_cases %>% gg_r_scatter("SCORE", "tIgE", "EOS", "OMNI EA Cases EH(+) & EH(-)")
eos_phenos_cases %>% gg_r_scatter("SCORE", "EASI", "EOS", "OMNI EA Cases EH(+) & EH(-)")
eos_phenos_cases %>% gg_r_scatter("SCORE", "RL", "EOS", "OMNI EA Cases EH(+) & EH(-)")

eos_phenos_controls <- eos_phenos %>% filter(DIAGROUP == "Non-Atopic")
eos_phenos_controls %>% gg_r_scatter("SCORE", "EOS", "tIgE", "OMNI EA Controls")
```



```{r AA_MEGA_AD}
eos_prs <- read_table("beta_score_eos_prs_AA.profile", col_types = "ccdddd")
pheno <- read_tsv("ADRN_MEGA_AA_1113_adjusted_severity_phenotypes2.txt", col_types = "ddccddcdddddd")

eos_phenos <- eos_prs %>%
  mutate(SampleID = str_extract(IID, "\\d{10}") %>% as.double) %>%
  left_join(pheno, by = "SampleID") %>%
  filter(! is.na(Pheno_ADNA))

eos_phenos %>%
  mutate(IID = SampleID, true_phens = Pheno_ADNA, PRS = SCORE) %>%
  # mutate(IID = SampleID, true_phens = RL_group, PRS = SCORE) %>%
  select(IID, true_phens, PRS) %>%
  write_csv("prs_file.txt")

eos_phenos %>%
  mutate(IID = SampleID, Age = AGE, Sex = GENDER, ancestry = "European") %>%
  select(IID, Age, Sex, RL, EASI, tIgE, ancestry) %>%
  write_csv("severity_file.txt")

gg_prs_violin_ca("MEGA AA EOS PRS vs AD Case/Control")
```

```{r AA_MEGA_scatter}
ggplot(eos_phenos, aes(x=EOS, y=SCORE, color = DIAGROUP)) +
  geom_point() + geom_smooth(method=lm, se=FALSE) +
  ggtitle("OMNI EA Cases & Controls -- SCORE vs AD")

gg_r_scatter <- function(.data, score, pheno, color, title_prefix) {
  m <- lm( as.formula(str_c(score, " ~ ", pheno)), .data)
  r2 <- str_c("r2 = ", format(summary(m)$r.squared, digits = 3))

  ggplot(.data, aes_string(x = pheno, y = score, color = color)) +
  geom_point() + geom_smooth(method=lm, se=FALSE) +
    geom_text(label = r2, x = -Inf, y = Inf, hjust = -0.5, vjust = 3) +
  ggtitle(str_c(title_prefix, " -- ", score, " vs ", pheno))
}

eos_phenos_cases <- eos_phenos %>% filter(DIAGROUP == "ADEH-")
eos_phenos_cases %>% gg_r_scatter("SCORE", "EOS", "tIgE", "OMNI EA Cases EH(+) & EH(-)")
eos_phenos_cases %>% gg_r_scatter("SCORE", "tIgE", "EOS", "OMNI EA Cases EH(+) & EH(-)")
eos_phenos_cases %>% gg_r_scatter("SCORE", "EASI", "EOS", "OMNI EA Cases EH(+) & EH(-)")
eos_phenos_cases %>% gg_r_scatter("SCORE", "RL", "EOS", "OMNI EA Cases EH(+) & EH(-)")

eos_phenos_controls <- eos_phenos %>% filter(DIAGROUP == "Non-Atopic")
eos_phenos_controls %>% gg_r_scatter("SCORE", "EOS", "tIgE", "OMNI EA Controls")
```

```{r AA_MEGA_grouped, eval = F}
eos_grouped_phenos <- eos_phenos %>%
  mutate(RL_group = ifelse(RL < 14.526365, 1, 2),
         # EASI_group = ifelse(EASI < 0.6993143, 1, 2)) %>%
         # EASI_group = ifelse(EASI < 1.017539, 1, 2)) %>%
         EASI_group = ifelse(EASI < 1.3142468, 1, 2),
  
         # tIgE_group = ifelse(tIgE < 1.3377471, 1, 2)) %>%
         # tIgE_group = ifelse(tIgE < 1.9118220, 1, 2)) %>%
         tIgE_group = ifelse(tIgE < 2.8043853, 1, 2)) %>%
  filter(! is.na(tIgE_group))

eos_grouped_phenos %>%
  # mutate(IID = SampleID, true_phens = Pheno_ADNA, PRS = SCORE) %>%
  # mutate(IID = SampleID, true_phens = RL_group, PRS = SCORE) %>%
  mutate(IID = SampleID, true_phens = tIgE_group, PRS = SCORE) %>%
  select(IID, true_phens, PRS) %>%
  write_csv("prs_file.txt")

eos_grouped_phenos %>%
  mutate(IID = SampleID, Age = AGE, Sex = GENDER, ancestry = "European") %>%
  select(IID, Age, Sex, RL, EASI, tIgE, ancestry) %>%
  write_csv("severity_file.txt")
```



